### ISSUE TITLE
Unfortunately mouse not working in win3.11

### ISSUE THREAD

**Issue by lukolszewski** [mborjesson/USB-Mouse-to-Serial#10]
I've tried the software with a DOS 386 retro PC runnign Windows 3.11. The mouse is detected correctly (I can see two messages saying Mouse connected), but there is no movement. I'm using the ATEN serial adapter and a multimeter verified null-modem cable.

I've also used the cute mouse driver in dos. This detects the mouse protocol correctly, but I can't tell if the mouse actually works under it as I have no dos software that uses the mouse to test.

I tried two different USB mice on the RPi side.

**Comment by lukolszewski** [comment]
I appears it is a hardware issue. The COM port in the DOS PC doesn't appear to be able to receive anything (sending works fine). So I'm closing this.

**Comment by mborjesson** [comment]
I hope you get it working!
