### ISSUE TITLE
Feature Request: Confirmation of selected Protocol

### ISSUE THREAD

**Issue by acmelab68** [mborjesson/USB-Mouse-to-Serial#2]
Hello

**UPDATE:** Sorry for this - I see it's in there already, right the first line. You may delete this. The last section starting with "Btw: ..." may be of interest though.
--- my mistake starts here ---
_I'd like to have a confirmation of the selected protocol at launch time on the command line.
Reason: I've entered 'mousesystem' and was leaving out the trailing 's' at the end. The application started normally without indicating it was falling back to the default protocol - which is Microsoft mode.
By selecting "Mouse Systems serial or bus mouse" in WIndows 3.11 WfW lead to a non working situation.
This took me quite a while to figure out._
--- my mistake ends here ---

Btw: The only working combination for Windows 3.11 WfW, Cute-Mouse and USB-Mouse-to-Serial was the "mousesystems" protocol. All permutations I've tried with Cutemouse v1.9, v.2.0 v2.1 and all the available protocols indicates, that only "mousesystems" is working in Windows 3.11 WfW.

**Comment by mborjesson** [comment]
Hi!

Hmm, you mean that only the "mousesystems" protocol works for you?
All protocols should work, I used ctmouse to verify they all worked using the mousetst-tool.
What does ctmouse tell you if you try to use the "microsoft" protocol? That's the one I'm using right now on my 486 (with the original Microsoft DOS-driver though).
