### ISSUE TITLE
USB to serial port adapter

### ISSUE THREAD

**Issue by powerMicha** [mborjesson/USB-Mouse-to-Serial#3]
Hi,
sorry, this is not any issue at all but I did not find another way to contact you. Which USB to serial port adapter did you use for your project?
kind regards
Micha

**Comment by mborjesson** [comment]
Hi!

No problem, it's okay to ask any questions here :)
I use an Aten UC232A (https://www.aten.com/global/en/products/usb-&-thunderbolt/usb-converters/uc232a/). It's the only adapter I've tried but it works flawlessly and requires no set up, just plug it in and you're ready to go.

**Comment by powerMicha** [comment]
Perfekt. Thank you so much!!


⁣Mobil gesendet.​

**Comment by mborjesson** [comment]
You're welcome! :)
