### ISSUE TITLE
Feature Request:  Translate other "modern" hardware

### ISSUE THREAD

**Issue by texneus** [mborjesson/USB-Mouse-to-Serial#6]
Have you considered emulating other modern devices into their "classic" counterparts?  The obvious scenario would be a USB keyboard into PS/2 or AT keyboard (I would imagine this requires the GPIO port to send/receive keyboard data to the host), but I'm sure other situations exist.

**Comment by mborjesson** [comment]
Yeah I have considered it, but I decided I wanted to keep this program simple and not locked to RasPi. I've been playing with idea of adding Gamepad-support for mouse control though just for fun.
In the future I might look at creating another app which can use RasPis features for things like this, but I can't say when that would happen.

Thanks for the suggestion!

**Comment by texneus** [comment]
Your welcome!  A separate program might be wiser.  Although PS/2 keyboards and AT adapters are still readily available now, I envision a time when, like serial mice, they are both scarce and inferior to modern components (I guess in comparison to a contemporary gaming keyboard less the bling, you could argue we are already there).
