### ISSUE TITLE
CuteMouse driver with this project

### ISSUE THREAD

**Issue by Ozzyboshi** [mborjesson/USB-Mouse-to-Serial#8]
Maybe it's worth mentioning in the readme that cutemouse works fine with this project?
http://cutemouse.sourceforge.net/
I am using this driver to enable the mouse in a real pentium 150 pc with win98.
If you boot in DOS mode the mouse does not work, usually the mouse back in they days, included a floppy disk with some installation process that add driver loading into autoexec.bat and config.sys.
Since this project does not ship the driver I thought It is worth mentioning to use cutemouse driver v2.0 to run old DOS software.

**Comment by mborjesson** [comment]
That's a good point, I've added it to the readme, thank you!
