### ISSUE TITLE
Full installation instructions?

### ISSUE THREAD

**Issue by davedoc1984** [mborjesson/USB-Mouse-to-Serial#9]
Is there any simple step by step instructions on how to install this with a Pi 3B? 

I am unsure how to install this.

**Comment by mborjesson** [comment]
The easiest way to download the files would be to clone the repository. If you run
`git clone git@github.com:mborjesson/USB-Mouse-to-Serial.git`
the code will be downloaded in a folder called USB-Mouse-to-Serial. cd into it and then follow the installation-instructions from the readme to compile and install.
